var bingoItems = [
    // Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
    "Biggoron Sword found",
    "Hookshot from Roofio",
    "Second magic in Shadow Temple",
    "Item or Song is VANILLA",
    "30+ skulls",
    "Ice Cavern entered before 90 minutes",
    "Chickens (Kakariko)",
    "GTG Toilet",
    "Comms off the rails", 
    "Emotional Support Fish",
    "Comms makes a pun", //puts intention in charge of bingo rather than luck
    "Richard's mom is a cheapskate (20 rupees or less)",
    "OoT is picked up",
    "Morpha Quick Grab",
    "Tennis Troll (PG or GD)",
    "Comms mentions MQ dungeons",
    "Deku Shield burns away",
    "Link gets Frozen",
    "Forced to wait for Time of Day",
    "Spirit Temple key logic",
    "Water Temple key logic",
    "Fire Temple key logic",
    "Haunted Wasteland is foolish",
    "Hyrule Castle is foolish",
    "Outside Ganon's Castle is foolish",
    "Void out",  
    "HBA Score < 1550",
    "Songs R Hard",
    "Double Defense located",
    "Tunic/Wallet in Path location", 
    "Stone Dungeon Boss required by Logic",
    "Chicken Abandons Link",
    "Iron Knuckle Death",
    "Burn timer death",
    "Drown Timer Death", 
    "Missing Always Hint at 90 minutes",
    "Missing Path Hint at 90 minutes", 
    "Hard AD discovered after 60 minutes", 
    "Racer gets bailed out after missing logic",
    "Dark Link found a way",
    "Foolish Hint in the Foolish location", 
    "Path hints leading to same item",
    "Oops, All Dungeons!",
    "Oops, World Tour!",
    "Reverse Wasteland",
    "Mido Skip",
    "King Zora/Mweep Skip",
    "Chat guesses TCG Correctly",
    "Ride a bean plant",
    "Dig skulls out of the dirt",
    "Push Armos Statue",
    "Ice Cavern Block Push",
    "Ice Cavern Glitchless Jump",
    "Racers in same dungeon simultaneously",
    "Hover Boots",
    "Iron Boots",
    "Din's Fire",
    "Farore's Wind",
    "Nayru's Love",
    "Fire Arrows",
    "Ice Arrows",
    "Stone of Agony", 
    "Lens of Truth", //disable in league settings
    "Validation Rupee/Greg",
    "Winner PoH",
    "Meme% located",
    "Fashion% located",
    "Shoe% located",
    "Spell% located",
    "Bottle% located",
    "Fairy revival"    
    
    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
