var bingoItems = [
    // Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
    "Carmelita on screen",
    "Someone voids",
    "Console crash",
    "carmWarm",
    "Remo does Slyence",
    "chat mentions sly 5",
    "Galleth says Fortnite",
    "Runner misses any form of Paris Skip - Sly 1",
    "missedsquareboost.com",
    "Runner fails Pirate Talk",
    "SlyGolds.com sponsorship/shoutout",
    "Scam Train",
    "Gift sub(s)",
    "Chat is lewd",
    "carmWarm",
    "Oggy is fat",
    "Someone voids",
    "Console crash",
    "carmWarm",
    "Remo does Slyence",
    "chat mentions sly 5",
    "Galleth says Fortnite",
    "Runner misses any form of Paris Skip - Sly 1",
    "missedsquareboost.com",
    "Runner fails Pirate Talk",
    "SlyGolds.com sponsorship/shoutout",
    "Scam Train",
    "Gift sub(s)",
    "Chat is lewd",
    "carmWarm",
    "Oggy is fat",
    "TRUCKIN"

    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
