var bingoItems = [
    // Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
    "Biggoron Sword found",
    "Hookshot from Roofio (man on roof in Kakariko)",
    "Second magic in Shadow Temple",
    "Item or Song is VANILLA",
    "30+ Skulltullas required",
    "Ice Cavern entered before 90 minutes",
    "Chickens (Kakariko) check completed",
    "GTG Toilet (sunken silver rupees) check completed",
    "Emotional Support Fish (fish in a bottle) located",
    "Commentators make a pun", //puts intention in charge of bingo rather than luck
    "Richard's mom is a cheapskate (ammo or <50 rupees)",
    "OoT is picked up",
    "Morpha Quick Grab",
    "Tennis Troll (Phantom Ganon or Ganondorf)",
    //"Commentators mention MQ dungeons", too specific to specific comms
    "Deku Shield burns away",
    "Link gets frozen",
    "Racer forced to wait for Time of Day",
    "Spirit Temple key logic",
    "Water Temple key logic", //needs to be more fleshed out
    "Fire Temple key logic",
    "Haunted Wasteland is foolish",
    "Hyrule Castle is foolish",
    "Outside Ganon's Castle is foolish",
    "Racer voids out",
    "Racer scores 1550 or less on Horseback Archery",
    "Songs are hard (racer has to retry playing song)",
    "Double Defense located",
    "Tunic or Wallet in Path location", 
    "Stone Dungeon Boss required by Logic",
    "Chicken abandons Link",
    "Crush death",
    "Link dies to an Iron Knuckle",
    "Link dies to the burn timer",
    "Link dies to the drown timer",
    "Missing *UNIQUE* Always Hint at 90 minutes", //change to 60?
    "Missing *UNIQUE* Path Hint at 90 minutes", //change to 60?
    "Hard AD discovered after 60 minutes or more",
    //"Racer gets bailed out", need to define better
    "Dark Link finds a way",
    "Foolish Hint in the *same* Foolish location", 
    "Multiple Path hints leading to same item",
    "Oops, All Dungeons!",
    "Oops, World Tour!",
    "Racer reverses through Haunted Wasteland",
    "Mido Skip",
    "King Zora (\"Mweep\") Skip",
    "Chat guesses TCG correctly",
    "Link rides a bean plant",
    "Link digs a Skulltulla out of a soil patch",
    "Link pushes an Armos Statue",
    "Ice Cavern Block Push",
    "Ice Cavern Glitchless Jump",
    "Racers in same dungeon simultaneously",
    "Hover Boots located",
    "Iron Boots located",
    "Din's Fire located",
    "Farore's Wind located",
    "Nayru's Love located",
    "Fire Arrows located",
    "Ice Arrows located",
    "Stone of Agony located", 
    //"Lens of Truth located", //disable in league settings
    "Validation Rupee/GREG located",
    "Winner PoH located",
    "Meme% located",
    "Fashion% located (boots and shirts)",
    "Shirt% located",
    "Shoe% located",
    "Spell% located",
    "Bottle% located",
    "Link gets revived by a Fairy in a bottle",
    "Market Drawbridge Rupee farming",
    "Dampé hits a fireball",
    "Chicken blocks Bombchu bowling",
    "Skull Mask check complete",
    "Racer sees Darunia's dance (plays song other than Saria's)",
    "Racer mis-times Goron Pot bomb throw",
    "Gold Gauntlets are bait",
    "Bait of the Well (no useful item in Well)",
    "Racer takes 2 cycles or more to beat Gohma",
    "Light Arrows inside Ganon's castle",
    "Fire BK on Pierre or Hammer chest",
    "NUTgrade (Racer finds a Deku Nut capacity upgrade)",
    "Racer executes B1 Skip in Deku Tree",
    "Back of Shadow not required",
    "2 or more paths leading to one boss",
    "Water is wet (Kakariko is a Path location)",
    "Medallion dungeon foolish",
    "Stone Dungeon is a Path location",
    "Racer enters Bottom of the Well without ZL *OR* bombs",
    "Racer save-scums to preserve keys",
    "Light Arrows hint from Ganondorf *REQUIRED*",
    "Racer completes either Frogs check",
    "Racer uses Bombchus against King Dodongo",
    "Racer buys a Shield",
    "back of lake hints read",
    "#FreetheGorons - talk to a goron in fire temple",
    "Dancing dad check completed",
    "Hit the hint stone",
    "complete an adult (vanilla) dungeon without a logically required item",
    "Enabled trick logically required",
    "Racer breaks out of logic", //freebie?
    "Nice rupee count called out",
    "Song is path item",
    "Bombchus found before first bomb bag (any racer)"
    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
